version: '3.8'

services:
  satellite-gis-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - KERAS_BACKEND=torch
      - PORT=5000
    volumes:
      - ./backend/static:/app/backend/static
      - ./backend/model:/app/backend/model
    restart: always
